# AUTOGENERATED FROM 'dbschema/queries/facility/all_facilities.edgeql' WITH:
#     $ edgedb-py --target blocking


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class AllFacilitiesResult(NoPydanticValidation):
    id: uuid.UUID
    name: str


def all_facilities(
    executor: edgedb.Executor,
) -> list[AllFacilitiesResult]:
    return executor.query(
        """\
        select company::Facilities {
            id,
            name,
        }\
        """,
    )
