# AUTOGENERATED FROM 'dbschema/queries/facility/create.edgeql' WITH:
#     $ edgedb-py --target blocking


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateResult(NoPydanticValidation):
    id: uuid.UUID


def create(
    executor: edgedb.Executor,
    *,
    name: str,
    address: str,
    city: str,
    state: str,
) -> CreateResult:
    return executor.query_single(
        """\
        insert company::Facilities {
            name := <str>$name,
            address := <str>$address,
            city := <str>$city,
            state := <str>$state,
        }\
        """,
        name=name,
        address=address,
        city=city,
        state=state,
    )
