# AUTOGENERATED FROM 'dbschema/queries/facility/get.edgeql' WITH:
#     $ edgedb-py --target blocking


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    address: str | None
    city: str | None
    state: str | None


def get(
    executor: edgedb.Executor,
    *,
    id: uuid.UUID,
) -> GetResult | None:
    return executor.query_single(
        """\
        select company::Facilities {
            id,
            name,
            address,
            city,
            state,
            }
            filter .id = <uuid>$id\
        """,
        id=id,
    )
