# AUTOGENERATED FROM 'dbschema/queries/facility/update.edgeql' WITH:
#     $ edgedb-py --target blocking


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateResult(NoPydanticValidation):
    id: uuid.UUID


def update(
    executor: edgedb.Executor,
    *,
    id: uuid.UUID,
    name: str,
    address: str,
    city: str,
    state: str,
) -> UpdateResult | None:
    return executor.query_single(
        """\
        update company::Facilities
            filter .id = <uuid>$id
            set {
                name := <str>$name,
                address := <str>$address,
                city := <str>$city,
                state := <str>$state,
            }\
        """,
        id=id,
        name=name,
        address=address,
        city=city,
        state=state,
    )
