# AUTOGENERATED FROM 'dbschema/queries/company/all_companies.edgeql' WITH:
#     $ edgedb-py --target blocking


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class AllCompaniesResult(NoPydanticValidation):
    id: uuid.UUID
    name: str


def all_companies(
    executor: edgedb.Executor,
) -> list[AllCompaniesResult]:
    return executor.query(
        """\
        select company::Company {
                id,
                name,
        }\
        """,
    )
