# AUTOGENERATED FROM 'dbschema/queries/company/create_company.edgeql' WITH:
#     $ edgedb-py --target blocking


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateCompanyResult(NoPydanticValidation):
    id: uuid.UUID


def create_company(
    executor: edgedb.Executor,
    *,
    name: str,
) -> CreateCompanyResult:
    return executor.query_single(
        """\
        insert company::Company {
            name := <str>$name,
        }\
        """,
        name=name,
    )
