# AUTOGENERATED FROM 'dbschema/queries/company/delete_company.edgeql' WITH:
#     $ edgedb-py --target blocking


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class DeleteCompanyResult(NoPydanticValidation):
    id: uuid.UUID


def delete_company(
    executor: edgedb.Executor,
    *,
    id: uuid.UUID,
) -> DeleteCompanyResult | None:
    return executor.query_single(
        """\
        delete company::Company
                    filter .id = <uuid>$id\
        """,
        id=id,
    )
