# AUTOGENERATED FROM 'dbschema/queries/company/get_company.edgeql' WITH:
#     $ edgedb-py --target blocking


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetCompanyResult(NoPydanticValidation):
    id: uuid.UUID
    name: str


def get_company(
    executor: edgedb.Executor,
    *,
    id: uuid.UUID,
) -> GetCompanyResult | None:
    return executor.query_single(
        """\
        select company::Company {
                        id,
                        name,
                    }
                    filter .id = <uuid>$id\
        """,
        id=id,
    )
