# AUTOGENERATED FROM 'dbschema/queries/company/remove_facility_from_company.edgeql' WITH:
#     $ edgedb-py --target blocking


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class RemoveFacilityFromCompanyResult(NoPydanticValidation):
    id: uuid.UUID


def remove_facility_from_company(
    executor: edgedb.Executor,
    *,
    company_id: uuid.UUID,
    facility_id: uuid.UUID,
) -> RemoveFacilityFromCompanyResult | None:
    return executor.query_single(
        """\
        update company::Company 
          filter .id=<uuid>$company_id
          set {
            facility -= (select detached company::Facilities 
                         filter .id=<uuid>$facility_id )
          }\
        """,
        company_id=company_id,
        facility_id=facility_id,
    )
