# AUTOGENERATED FROM 'dbschema/queries/company/update_company_name.edgeql' WITH:
#     $ edgedb-py --target blocking


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateCompanyNameResult(NoPydanticValidation):
    id: uuid.UUID


def update_company_name(
    executor: edgedb.Executor,
    *,
    id: uuid.UUID,
    name: str,
) -> UpdateCompanyNameResult | None:
    return executor.query_single(
        """\
        update company::Company
            filter .id = <uuid>$id
            set {
                name := <str>$name,
            }\
        """,
        id=id,
        name=name,
    )
